export const ROUTES = {
  MAIN: 'MAIN' as const,
  DASHBOARD: 'DASHBOARD' as const,
  ONBOARDING: 'ONBOARDING' as const,
  QRCODESCAN: 'QRCODESCAN' as const,
  BIOMETRIC: 'BIOMETRIC' as const,
  CREATE_PAYMENT: 'CREATE_PAYMENT' as const,
  PAYMENT_DETAILS: 'PAYMENT_DETAILS' as const,
  PAYMENTS: 'PAYMENTS' as const,
  NOT_FOUND: 'NOT_FOUND' as const,
  PAYMENT_HISTORY: 'PAYMENT_HISTORY' as const,
  MYASSET_SCREEN: 'MYASSET_SCREEN' as const,
};
