export const STORAGE = {
  BIOMETRIC_ENABLED: '@KITAI_PAY:BIOMETRIC_ENABLED',
  IS_FIRST_LAUNCH: '@KITAI_PAY:IS_FIRST_LAUNCH',
};

export const TOKEN_OPTIONS = [
  'MATIC',
  'USDC',
  'USDT',
  'DAI',
  'WBTC',
  'WETH',
  'WMATIC',
  'WUSDC',
];
