export const STORAGE = {
  BIOMETRIC_ENABLED: '@KITAI_PAY:BIOMETRIC_ENABLED',
  IS_FIRST_LAUNCH: '@KITAI_PAY:IS_FIRST_LAUNCH',
  USER_ADDRESS: '@KITAI_PAY:USER_ADDRESS',
  USER_ID: '@KITAI_PAY:USER_ID',
  USER_TOKEN: '@KITAI_PAY:USER_TOKEN',
};

export const TOKEN_OPTIONS = [
  'MATIC',
  'USDC',
  'USDT',
  'DAI',
  'WBTC',
  'WETH',
  'WMATIC',
  'WUSDC',
];
